spring.application.name=cronograma
# Puerto del microservicio (según doc al cronograma le corresponde 8085)
server.port=8085

# Conexión a mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_cronograma_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (Crea/Actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ── DDL AUTO ────────────────────────────────────────
# update: crea las tablas si no existen, las actualiza
# si el modelo cambió. Ideal para desarrollo en clase.
#spring.jpa.hibernate.ddl-auto=create-drop